### PR TITLE
Implement interviewer can see own current and next week time slots

### PR DESCRIPTION
**Pull request by R-accoo-n**
Implement interviewer can see own current and next week time slots

### CODE REVIEW

**Comment by julse-lia** [comment]
|File|Coverage [74.37%]|:green_apple:|
|:-|:-:|:-:|
|[InterviewerService.java](https://github.com/julse-lia/intellistart-java-2022-klonn/blob/ae5bcea2731408984ddc91de026cbce627309dc5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|83.28%|:green_apple:|
|[InterviewerController.java](https://github.com/julse-lia/intellistart-java-2022-klonn/blob/ae5bcea2731408984ddc91de026cbce627309dc5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|0%|:x:|

|Total Project Coverage|67.64%|:green_apple:|
|:-|:-:|:-:|

**Comment by julse-lia** [comment]
|File|Coverage [74.37%]|:green_apple:|
|:-|:-:|:-:|
|[InterviewerService.java](https://github.com/julse-lia/intellistart-java-2022-klonn/blob/ae5bcea2731408984ddc91de026cbce627309dc5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|83.28%|:green_apple:|
|[InterviewerController.java](https://github.com/julse-lia/intellistart-java-2022-klonn/blob/ae5bcea2731408984ddc91de026cbce627309dc5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|0%|:x:|

|Total Project Coverage|67.64%|:green_apple:|
|:-|:-:|:-:|

**Comment by julse-lia** [comment]
|File|Coverage [74.37%]|:green_apple:|
|:-|:-:|:-:|
|[InterviewerService.java](https://github.com/julse-lia/intellistart-java-2022-klonn/blob/ae5bcea2731408984ddc91de026cbce627309dc5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|83.28%|:green_apple:|
|[InterviewerController.java](https://github.com/julse-lia/intellistart-java-2022-klonn/blob/ae5bcea2731408984ddc91de026cbce627309dc5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|0%|:x:|

|Total Project Coverage|67.64%|:green_apple:|
|:-|:-:|:-:|

**Comment by julse-lia** [comment]
|File|Coverage [72.3%]|:green_apple:|
|:-|:-:|:-:|
|[InterviewerService.java](https://github.com/julse-lia/intellistart-java-2022-klonn/blob/489fd795454eee4154fd98ee9dc6e95a368ee90c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|81.31%|:green_apple:|
|[InterviewerController.java](https://github.com/julse-lia/intellistart-java-2022-klonn/blob/489fd795454eee4154fd98ee9dc6e95a368ee90c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FInterviewerController.java)|0%|:x:|

|Total Project Coverage|68%|:green_apple:|
|:-|:-:|:-:|

**Review by tarasreznik — APPROVED** [review]

**Pull request merged**
